### ISSUE TITLE
Publish for Scala 3.x

### ISSUE THREAD

**Issue by jdegoes** [scala-js/scala-js-weakreferences#6]

**Comment by sjrd** [comment]
This is a library for part of the JDK. The source and binary interfaces is 100% identical between 2.13 and 3, and will remain so forever. Also it was initially part of scalajs-library, whose 2.13 version is used for Scala 3 at all times. So this library is meant to be used with the 2.13 version for Scala 3 at all times as well. You can depend on it with
```scala
libraryDependencies += ("org.scala-js" %%% "scalajs-weakreferences" % "1.0.0").cross(CrossVersion.for3Use2_13)
```
